# Generated by Django 3.2.7 on 2022-02-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='followed',
        ),
    ]
