# Generated by Django 3.2.7 on 2022-03-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
