# Generated by Django 3.2.7 on 2022-03-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20220317_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/network/profile_pic.png', upload_to=''),
        ),
    ]
