# Generated by Django 3.2.7 on 2022-03-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20220328_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='profile_images/default_avatar  .png', upload_to='profile_images'),
        ),
    ]
