# Generated by Django 3.2.7 on 2022-03-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(),
        ),
    ]
