# Generated by Django 4.0.4 on 2022-05-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_auto_20220328_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='profile_pics/default_avatar.png', upload_to='profile_pics'),
        ),
    ]
